name: crypto_deribit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - pandas>=1.3.0
  - plotly>=5.3.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - tqdm>=4.62.0
  - requests>=2.26.0
  - python-dateutil>=2.8.2
  - pip>=21.0
  - pip:
    - yfinance>=0.1.70
    - python-dotenv>=0.19.0
    - websockets>=10.0
    - ratelimit>=2.2.1