name: anomaly_option
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas=2.0.0
  - numpy=1.24.0
  - plotly=5.18.0
  - requests=2.31.0
  - python-dotenv=1.0.0
  - scipy=1.11.0
  - statsmodels=0.14.0
  - tqdm=4.66.0
  - dash=2.14.0
  - dash-bootstrap-components=1.5.0
  - pip:
    - yfinance==0.2.36
    - websockets==10.0
    - ratelimit==2.2.1
    - pytest==7.4.0
    - pytest-cov==4.1.0
    - black==23.7.0
    - isort==5.12.0
    - flake8==6.1.0
    - mypy==1.5.0
    - streamlit==1.32.0